ALTER TABLE Treatment DROP CONSTRAINT FK_Treatment_patient_fk
ALTER TABLE Treatment DROP CONSTRAINT FK_Treatment_providers_fk
ALTER TABLE DrugTreatment DROP CONSTRAINT FK_DrugTreatment_TREATMENTID
ALTER TABLE Surgery DROP CONSTRAINT FK_Surgery_TREATMENTID
ALTER TABLE Radiology DROP CONSTRAINT FK_Radiology_TREATMENTID
DROP TABLE Patient CASCADE
DROP TABLE Provider CASCADE
DROP TABLE Treatment CASCADE
DROP TABLE DrugTreatment CASCADE
DROP TABLE Surgery CASCADE
DROP TABLE Radiology CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
