apiVersion: apps/v1
kind: Deployment
metadata:
 name: cs548-rest
spec:
 replicas: 1
 selector:
 matchLabels:
 app: cs548-rest
 template:
 metadata:
 labels:
 app: cs548-rest
 spec:
 restartPolicy: Always
 containers:
 - name: cs548-rest
 image: cs548/rest
 env:
 - name: DATABASE_PASSWORD
 value: YYYYYY
 - name: MQ_PASSWORD
 value: ZZZZZZ
 imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
 name: cs548-rest
 labels:
 app: cs548-rest
spec:
 type: LoadBalancer
 ports:
 - name: http
 port: 8080
 - name: https
 Port: 8181
 selector:
 app: cs548-rest

